Algoritmo "entrada e saída de dados"
// Descrição   : "entrada e saída de dados"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/11/2021
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval ("Digite seu nome")
leia (nome)
Escreval ("Digite sua nota")
Leia (nota)

Escreval ("O nome digitado foi", nome)
Escreval ("A nota digitada foi", nota)

Fimalgoritmo